<?php

use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([

            ['pinyin' => 'Ai Ye','latin_name' => 'Artemisia Argyifolium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Mugwort leaf'],
            ['pinyin' => 'Ai Ye (Tan)','latin_name' => 'Artemisiae Argyi Folium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Charred mugwort leaf'],
            ['pinyin' => 'Ba Ji Tian','latin_name' => 'Morindae Officinalis Radix','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Morinda root'],
            ['pinyin' => 'Bai Bian Dou','latin_name' => 'Lablab Semen Album','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lablab bean'],
            ['pinyin' => 'Bai Bu','latin_name' => 'Stemonae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Stemona root'],
            ['pinyin' => 'Bai Dou Kou','latin_name' => 'Amomi Fructus Rotundus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Cardamom'],
            ['pinyin' => 'Bai Fu Zi','latin_name' => 'Typhonii Gigantei Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Typhonium rhizome'],
            ['pinyin' => 'Bai Guo','latin_name' => 'Ginkgo Semen','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Ginkgo nut'],
            ['pinyin' => 'Bai He','latin_name' => 'Lilii Bulbus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lily bulb'],
            ['pinyin' => 'BAI HU TANG','latin_name' => 'BAI HU TANG','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'BAI HU TANG'],
            ['pinyin' => 'Bai Hua She She Cao','latin_name' => 'Hedyotis Diffusae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Oldenlandia'],
            ['pinyin' => 'Bai Ji','latin_name' => 'Bletillae Rhizoma','concentration' => '*1:1','costPerGram' => '0.20','common_name' => 'Bletilla root'],
            ['pinyin' => 'Bai Jiang Cao','latin_name' => 'Patriniae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Patrinia'],
            ['pinyin' => 'Bai Jie Zi','latin_name' => 'Sinapis Albae Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'White mustard seed'],
            ['pinyin' => 'Bai Mao Gen','latin_name' => 'Imperatae Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Imperata root'],
            ['pinyin' => 'Bai Qian','latin_name' => 'Cynanchi Stauntonii Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Willowleaf swallowwort rhizome'],
            ['pinyin' => 'Bai Shao','latin_name' => 'Paeoniae Radix Alba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'White peony raw'],
            ['pinyin' => 'Bai Shao (Chao)','latin_name' => 'Paeoniae Radix Alba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'White peony stir-fried'],
            ['pinyin' => 'Bai Tou Weng','latin_name' => 'Pulsatillae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Pulsatilla root'],
            ['pinyin' => 'Bai Wei','latin_name' => 'Cynanchi Atrati Radix','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Black swallowwort'],
            ['pinyin' => 'Bai Xian Pi','latin_name' => 'Dictamni Cortex','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Dictamnus bark'],
            ['pinyin' => 'Bai Zhi','latin_name' => 'Angelicae Dahuricae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Dahurian angelica'],
            ['pinyin' => 'Bai Zhu','latin_name' => 'Atractylodis Macrocephalae Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'White atractylodes root'],
            ['pinyin' => 'Bai Zhu - Classical Pearls (TEMP OUT OF STOCK)','latin_name' => 'Atractylodis Macrocephalae Rhizoma','concentration' => '5:1','costPerGram' => '0.46','common_name' => 'Paozhi White atractylodes root'],
            ['pinyin' => 'Bai Zhu (Chao)','latin_name' => 'Atractylodis Macrocephalae Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'White atractylodes root stir-fried'],
            ['pinyin' => 'Bai Zi Ren','latin_name' => 'Platycladi Semen Also called Biotae Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Arborvitae seed'],
            ['pinyin' => 'Ban Lan Gen','latin_name' => 'Isatidis Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Isatis root'],
            ['pinyin' => 'Ban Xia (Fa)','latin_name' => 'Pinelliae Rhizoma','concentration' => '5:1','costPerGram' => '0.32','common_name' => 'Pinellia standard'],
            ['pinyin' => 'Ban Xia (Fa) - Classical Pearls','latin_name' => 'Pinellia ternata','concentration' => '5:1','costPerGram' => '0.60','common_name' => 'paozhi Pinellia standard'],
            ['pinyin' => 'Ban Xia (Jiang)','latin_name' => 'Pinelliae Rhizoma','concentration' => '5:1','costPerGram' => '0.32','common_name' => 'Pinellia ginger-processed'],
            ['pinyin' => 'Ban Xia (Sheng) - Classical Pearls','latin_name' => 'Pinellia ternata','concentration' => '5:1','costPerGram' => '0.60','common_name' => 'Pinellia unprocessed'],
            ['pinyin' => 'BAN XIA HOU PO TANG (not cooked together)','latin_name' => 'BAN XIA HOU PO TANG (not cooked together)','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'BAN XIA HOU PO TANG (not cooked together)'],
            ['pinyin' => 'BAO HE WAN','latin_name' => 'BAO HE WAN','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'BAO HE WAN'],
            ['pinyin' => 'Bei Sha Shen','latin_name' => 'Adenophorae seu Glehniae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Glehnia root'],
            ['pinyin' => 'Bi Xie','latin_name' => 'Dioscoreae Hypoglaucae Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Fish poison yam'],
            ['pinyin' => 'Bian Xu','latin_name' => 'Polygoni Avicularis Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Knotgrass'],
            ['pinyin' => 'Bie Jia','latin_name' => 'Trionycis Carapax','concentration' => '5:1','costPerGram' => '0.40','common_name' => 'Turtle shell'],
            ['pinyin' => 'Bing Lang','latin_name' => 'Arecae Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Areca Seed'],
            ['pinyin' => 'Bo He','latin_name' => 'Menthae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Mint'],
            ['pinyin' => 'Bu Gu Zhi','latin_name' => 'Psoraleae Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Psoralea fruit'],
            ['pinyin' => 'Can Sha','latin_name' => 'Bombycis Faeces','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Silkworm droppings'],
            ['pinyin' => 'Cang Er Zi','latin_name' => 'Xanthii Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Xanthium fruit'],
            ['pinyin' => 'Cang Zhu','latin_name' => 'Atractylodis Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Red Atractylodes root'],
            ['pinyin' => 'Cang Zhu - Classical Pearls','latin_name' => 'Atractylodis lancea Rhizoma','concentration' => '5:1','costPerGram' => '0.35','common_name' => 'Paozhi Red Atractylodes root'],
            ['pinyin' => 'Cao Wu (Zhi) - Classical Pearls','latin_name' => 'Aconitum kusnetzoffii','concentration' => '5:1','costPerGram' => '0.35','common_name' => 'Jiangyou Fuyang Aconite'],
            ['pinyin' => 'Ce Bai Ye','latin_name' => 'Platycladi Cacumen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Arborvitae leaf'],
            ['pinyin' => 'CHAI GE JIE JI TANG','latin_name' => 'CHAI GE JIE JI TANG','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'CHAI GE JIE JI TANG'],
            ['pinyin' => 'Chai Hu','latin_name' => 'Bupleuri Radix','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Bupleurum root'],
            ['pinyin' => 'CHAI HU JIA LONG GU MU LI TANG','latin_name' => 'CHAI HU JIA LONG GU MU LI TANG','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'CHAI HU JIA LONG GU MU LI TANG'],
            ['pinyin' => 'Chan Tui','latin_name' => 'Cicadae Periostracum','concentration' => '5:1','costPerGram' => '0.38','common_name' => 'Cicada molting'],
            ['pinyin' => 'Chang Shan','latin_name' => 'Dichroa Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Dichroa Root'],
            ['pinyin' => 'Mai Ya (Chao)','latin_name' => 'Hordei Fructus Germinatus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Barley sprout dry-fried'],
            ['pinyin' => 'Che Qian Cao','latin_name' => 'Plantaginis Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Plantago'],
            ['pinyin' => 'Che Qian Zi','latin_name' => 'Plantaginis Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Plantago seed'],
            ['pinyin' => 'Chen Pi','latin_name' => 'Citri Reticulatae Pericarpium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Tangerine peel'],
            ['pinyin' => 'Chen Xiang','latin_name' => 'Aquilariae Lignum Resinatum','concentration' => '*1:1','costPerGram' => '0.75','common_name' => 'Aquilaria wood'],
            ['pinyin' => 'Chi Fu Ling','latin_name' => 'Poriae Cocos Rubrae','concentration' => '5:1','costPerGram' => '0.34','common_name' => 'Red Poria'],
            ['pinyin' => 'Chi Shao','latin_name' => 'Paeoniae Radix Rubra','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Red peony root'],
            ['pinyin' => 'Chi Shi Zhi','latin_name' => 'Halloysitum rubrum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Halloysite'],
            ['pinyin' => 'Chi Xiao Dou','latin_name' => 'Phaseoli Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Rice bean'],
            ['pinyin' => 'Chuan Bei Mu','latin_name' => 'Fritillariae Cirrhosae Bulbus','concentration' => '*1:1','costPerGram' => '0.40','common_name' => 'Sichuan fritillaria bulb'],
            ['pinyin' => 'Chuan Lian Zi','latin_name' => 'Toosendan Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Toosendan fruit'],
            ['pinyin' => 'Chuan Niu Xi','latin_name' => 'Cyathulae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Cyathula root'],
            ['pinyin' => 'Chuan Wu Zhi/Wu Tou - Classical Pearls','latin_name' => 'Aconiti carmicheli Radix','concentration' => '5:1','costPerGram' => '0.45','common_name' => 'Jiangyou Fuyang Aconite mother root'],
            ['pinyin' => 'Zhi Chuan Wu/Wu Tou - Classical Pearls','latin_name' => 'Aconiti carmicheli Radix','concentration' => '5:1','costPerGram' => '0.45','common_name' => 'Jiangyou Fuyang Aconite mother root'],
            ['pinyin' => 'Chuan Xin Lian','latin_name' => 'Andrographitis Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Andrographis'],
            ['pinyin' => 'Chuan Xiong','latin_name' => 'Chuanxiong Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Chuanxiong rhizome'],
            ['pinyin' => 'Chun Pi','latin_name' => 'Ailanthis Cortex','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Toona Bark'],
            ['pinyin' => 'Ci Shi','latin_name' => 'Magnetitum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Loadstone'],
            ['pinyin' => 'Ci Wu Jia/Wu Jia Shen','latin_name' => 'Eleutherococci Senticosi Radix et Caulis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Siberian ginseng'],
            ['pinyin' => 'Wu Jia Shen/Ci Wu Jia','latin_name' => 'Eleutherococci Senticosi Radix et Caulis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Siberian ginseng'],
            ['pinyin' => 'Cong Bai','latin_name' => 'Allii Fistulosi Bulbus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Scallion/Spring Onion'],
            ['pinyin' => 'Da Fu Pi','latin_name' => 'Arecae Pericarpium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Areca husk'],
            ['pinyin' => 'Da Huang','latin_name' => 'Rhei Radix et Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Rhubarb'],
            ['pinyin' => 'Da Huang (Shu)','latin_name' => 'Rhei Radix et Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Processed/Cooked Rhubarb'],
            ['pinyin' => 'Da Ji','latin_name' => 'Cirsii Japonici Herba seu Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Euphorbia/knoxia root'],
            ['pinyin' => 'Da Qing Ye','latin_name' => 'Isatidis Folium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Isatis leaf'],
            ['pinyin' => 'Da Xue Teng','latin_name' => 'Sargentodoxae Caulis','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Sargentodoxa stem'],
            ['pinyin' => 'Da Zao','latin_name' => 'Jujubae Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Jujube'],
            ['pinyin' => 'Dai Zhe Shi','latin_name' => 'Haematitum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Hematite'],
            ['pinyin' => 'Dan Dou Chi','latin_name' => 'Sojae Semen Praeparatum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Fermented soybean'],
            ['pinyin' => 'Dan Nan Xing','latin_name' => 'Arisaema cum Bile','concentration' => '5:1','costPerGram' => '0.45','common_name' => 'Bile processed arisaema root'],
            ['pinyin' => 'Dan Shen','latin_name' => 'Salviae Miltiorrhizae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Salvia root'],
            ['pinyin' => 'Dan Zhu Ye','latin_name' => 'Lophatheri Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lophatherum'],
            ['pinyin' => 'Dang Gui','latin_name' => 'Angelicae Sinensis Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Chinese angelica'],
            ['pinyin' => 'Dang Gui - Classical Pearls','latin_name' => 'Angelicae Sinensis Radix','concentration' => '5:1','costPerGram' => '0.43','common_name' => 'paozhi Chinese angelica'],
            ['pinyin' => 'Dang Gui (Jiu)','latin_name' => 'Angelicae Sinensis Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Chinese angelica wine-processed'],
            ['pinyin' => 'Dang Gui (Wei)','latin_name' => 'Angelica sinensis radicis Cauda','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Chinese angelica root tail'],
            ['pinyin' => 'DANG GUI SHAO YAO SAN','latin_name' => 'DANG GUI SHAO YAO SAN','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'DANG GUI SHAO YAO SAN'],
            ['pinyin' => 'Dang Shen','latin_name' => 'Codonopsis Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Codonopsis root'],
            ['pinyin' => 'Deng Xin Cao','latin_name' => 'Junci medulla','concentration' => '5:1','costPerGram' => '0.30','common_name' => 'Juncus Pith'],
            ['pinyin' => 'Di Bie Chong','latin_name' => 'Eupolyphaga','concentration' => '5:1','costPerGram' => '0.34','common_name' => 'Wingless Cockroach'],
            ['pinyin' => 'Di Fu Zi','latin_name' => 'Kochiae Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Kochia fruit'],
            ['pinyin' => 'Di Gu Pi','latin_name' => 'Lycii Cortex','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lycium bark'],
            ['pinyin' => 'Di Long','latin_name' => 'Pheretima','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Earthworm'],
            ['pinyin' => 'Di Long (Zhi)','latin_name' => 'Pheretima','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'processed Earthworm'],
            ['pinyin' => 'Di Yu','latin_name' => 'Sanguisorbae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Sanguisorba root'],
            ['pinyin' => 'Di Yu Tan','latin_name' => 'Sanguisorbae Radix Carbonisatum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Charred Sanguisorba root'],
            ['pinyin' => 'Ding Xiang','latin_name' => 'Caryophylli Flos','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Clove'],
            ['pinyin' => 'Dong Chong Xia Cao','latin_name' => 'Cordyceps','concentration' => '4:1','costPerGram' => '0.40','common_name' => 'Cordyceps Powder 4 to 1 extract'],
            ['pinyin' => 'Dong Gua Zi','latin_name' => 'Benincasae Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Wax gourd seed'],
            ['pinyin' => 'Dong Kui Zi','latin_name' => 'Malvae Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Mallow seed'],
            ['pinyin' => 'Du Huo','latin_name' => 'Angelicae Pubescentis Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Pubescent angelica'],
            ['pinyin' => 'DU HUO JI SHENG TANG','latin_name' => 'DU HUO JI SHENG TANG','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'DU HUO JI SHENG TANG'],
            ['pinyin' => 'Du Zhong','latin_name' => 'Eucommiae Cortex','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Eucommia bark'],
            ['pinyin' => 'E Bu Shi Cao','latin_name' => 'Centipeda Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Centipeda'],
            ['pinyin' => 'E Jiao','latin_name' => 'Asini Corii Colla','concentration' => '5:1','costPerGram' => '0.38','common_name' => 'Ass hide glue'],
            ['pinyin' => 'E Zhu','latin_name' => 'Curcumae Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Curcuma rhizome'],
            ['pinyin' => 'Elder Berry','latin_name' => 'Sambucus Nigra','concentration' => '5:1','costPerGram' => '0.30','common_name' => 'Black Elder - extract'],
            ['pinyin' => 'ER CHEN TANG','latin_name' => 'ER CHEN TANG','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'ER CHEN TANG'],
            ['pinyin' => 'Fan Xie Ye','latin_name' => 'Sennae Folium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Senna leaf'],
            ['pinyin' => 'Fang Feng','latin_name' => 'Saposhnikoviae Radix','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Saposhnikovia'],
            ['pinyin' => 'Fang Ji','latin_name' => 'Stephaniae Tetrandrae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Stephania root'],
            ['pinyin' => 'Fei Shi - Classical Pearls','latin_name' => 'Torreya Semen','concentration' => '5:1','costPerGram' => '0.45','common_name' => 'Torreya seeds'],
            ['pinyin' => 'Fu Ling','latin_name' => 'Poria','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Poria'],
            ['pinyin' => 'Fu Ling Pi','latin_name' => 'Poriae Cutis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Poria skin'],
            ['pinyin' => 'Fu Pen Zi','latin_name' => 'Rubi Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Rubus berry'],
            ['pinyin' => 'Fu Ping','latin_name' => 'Spirodelae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Duckweed'],
            ['pinyin' => 'Fu Shen','latin_name' => 'Poria Sclerotium Pararadicis','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Root poria'],
            ['pinyin' => 'Fu Xiao Mai','latin_name' => 'Tritici Fructus Levis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Light wheat grain'],
            ['pinyin' => 'Fu Zi White - Classical Pearls','latin_name' => 'Aconiti Radix lateralis praeparata','concentration' => '5:1','costPerGram' => '0.60','common_name' => 'Paozhi Jiangyou Aconite'],
            ['pinyin' => 'Fu Zi Black - Classical Pearls','latin_name' => 'Aconiti Radix lateralis praeparata','concentration' => '5:1','costPerGram' => '0.65','common_name' => 'Paozhi Jiangyou Aconite'],
            ['pinyin' => 'Gan Cao','latin_name' => 'Glycyrrhizae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Licorice root'],
            ['pinyin' => 'Gan Jiang','latin_name' => 'Zingiberis Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Dried ginger'],
            ['pinyin' => 'Gan Jiang - Classical Pearls (TEMP OUT OF STOCK)','latin_name' => 'Zingiberis Rhizoma','concentration' => '5:1','costPerGram' => '0.32','common_name' => 'Sichuan Fuyang Ginger'],
            ['pinyin' => 'GAN MAI DA ZAO TANG','latin_name' => 'GAN MAI DA ZAO TANG','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'GAN MAI DA ZAO TANG'],
            ['pinyin' => 'Gan Sui','latin_name' => 'Kansui Radix','concentration' => '5:1','costPerGram' => '0.40','common_name' => 'Euphorbia'],
            ['pinyin' => 'Gao Ben','latin_name' => 'Ligustici Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Chinese lovage rhizome'],
            ['pinyin' => 'Gao Liang Jiang','latin_name' => 'Alpiniae Officinarum Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lesser galangal root'],
            ['pinyin' => 'Ge Gen','latin_name' => 'Puerariae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Pueraria root'],
            ['pinyin' => 'Ge Hua','latin_name' => 'Puerariae Flos','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Pueraria Flower'],
            ['pinyin' => 'Ge Jie','latin_name' => 'Gecko','concentration' => '5:1','costPerGram' => '0.95','common_name' => 'Gecko'],
            ['pinyin' => 'Geng Mi','latin_name' => 'Oryzae Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Rice'],
            ['pinyin' => 'Gou Ji','latin_name' => 'Cibotii Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Cibotium root'],
            ['pinyin' => 'Gou Qi Zi','latin_name' => 'Lycii Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lycium berry'],
            ['pinyin' => 'Gou Teng','latin_name' => 'Uncariae Ramulus cum Uncis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Uncaria stem and thorn'],
            ['pinyin' => 'Grape Seed','latin_name' => 'Vitis vinifera','concentration' => '5:1','costPerGram' => '0.30','common_name' => 'Pu Tao Zi'],
            ['pinyin' => 'Gu Jing Cao','latin_name' => 'Eriocauli Flos','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Eriocaulon flower'],
            ['pinyin' => 'Gu Sui Bu','latin_name' => 'Drynariae Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Drynaria root'],
            ['pinyin' => 'Gu Ya','latin_name' => 'Setariae Fructus Germinatus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Millet sprout'],
            ['pinyin' => 'Gua Lou','latin_name' => 'Tricosanthis Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Trichosanthes fruit'],
            ['pinyin' => 'Gua Lou Pi','latin_name' => 'Tricosanthis Pericarpium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Trichosanthes rind'],
            ['pinyin' => 'Gua Lou Ren/Zi','latin_name' => 'Tricosanthis Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Trichosanthes seed'],
            ['pinyin' => 'Guan Zhong','latin_name' => 'Cyrtomii Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Aspidium'],
            ['pinyin' => 'Gui Ban','latin_name' => 'Testudinis Plastrum','concentration' => '5:1','costPerGram' => '0.55','common_name' => 'Tortoise plastron'],
            ['pinyin' => 'Gui Jian Yu','latin_name' => 'Euonymus alatus','concentration' => '5:1','costPerGram' => '0.40','common_name' => 'Burning Bush leaves'],
            ['pinyin' => 'GUI PI TANG','latin_name' => 'GUI PI TANG','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'GUI PI TANG'],
            ['pinyin' => 'Gui Xin','latin_name' => 'Cinnamomi Inner Cortex','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Cinnamon Inner Bark'],
            ['pinyin' => 'Gui Zhi','latin_name' => 'Cinnamomi Ramulus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Cinnamon twig'],
            ['pinyin' => 'Gui Zhi Yuenan - Classical Pearls','latin_name' => 'Cinnamomum loureiroi','concentration' => '5:1','costPerGram' => '0.40','common_name' => 'Vietnamese Cinnamon'],
            ['pinyin' => 'GUI ZHI FU LING WAN','latin_name' => 'GUI ZHI FU LING WAN','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'GUI ZHI FU LING WAN'],
            ['pinyin' => 'GUI ZHI TANG','latin_name' => 'GUI ZHI TANG','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'GUI ZHI TANG'],
            ['pinyin' => 'Hai Feng Teng','latin_name' => 'Caulis Piperis Futokadsurae','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Kadsura pepper stem'],
            ['pinyin' => 'Hai Fu Shi','latin_name' => 'Costaziae Os/Pumex','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Costazia bone/pumice'],
            ['pinyin' => 'Hai Ge Fen','latin_name' => 'Cyclinae Sinensis Conchae','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Clam Shell'],
            ['pinyin' => 'Hai Jin Sha','latin_name' => 'Lygodii Spora','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lygodium spore'],
            ['pinyin' => 'Hai Piao Xiao','latin_name' => 'Sepiae Endoconcha','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Cuttlefish bone'],
            ['pinyin' => 'Hai Tong Pi','latin_name' => 'Erythrinae Cortex','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Erythrina bark'],
            ['pinyin' => 'Hai Zao','latin_name' => 'Sargassum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Sargassum'],
            ['pinyin' => 'Han Lian Cao / Mo Han Lian','latin_name' => 'Ecliptae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Eclipta'],
            ['pinyin' => 'He Huan Hua','latin_name' => 'Albizzia julibrissin','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Albizzia Flower'],
            ['pinyin' => 'He Huan Pi','latin_name' => 'Albiziae Cortex','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Silk tree bark'],
            ['pinyin' => 'He Shou Wu','latin_name' => 'Polygoni Multiflori Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Flowery knotweed root'],
            ['pinyin' => 'He Ye','latin_name' => 'Nelumbinis Folium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lotus leaf'],
            ['pinyin' => 'He Zi','latin_name' => 'Chebulae Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Chebule'],
            ['pinyin' => 'Hei Zhi Ma','latin_name' => 'Sesami Semen nigrum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Black Sesame Seed'],
            ['pinyin' => 'Hong Hua','latin_name' => 'Carthami Flos','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Carthamus flower'],
            ['pinyin' => 'Hong Jing Tian','latin_name' => 'Rhodiola Radix et Rhizoma','concentration' => '5:1','costPerGram' => '0.32','common_name' => 'Rhodiola Root'],
            ['pinyin' => 'Hou Po','latin_name' => 'Magnoliae Officinalis Cortex','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Officinal magnolia bark'],
            ['pinyin' => 'Hu Huang Lian','latin_name' => 'Picrorrhizae Rhizoma','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Picorrhiza rhizome'],
            ['pinyin' => 'Hu Po','latin_name' => 'Succinum','concentration' => '*1:1','costPerGram' => '0.20','common_name' => 'Amber'],
            ['pinyin' => 'Hu Tao Ren','latin_name' => 'Juglandis Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Walnut'],
            ['pinyin' => 'Hu Zhang','latin_name' => 'Polygoni Cuspidati Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Bushy knotweed root'],
            ['pinyin' => 'Hua Jiao','latin_name' => 'Zanthoxyli Pericarpium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Zanthoxylum husk'],
            ['pinyin' => 'Hua Shi','latin_name' => 'Talcum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Talcum'],
            ['pinyin' => 'Huai Hua','latin_name' => 'Sophorae Flos','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Sophora flower'],
            ['pinyin' => 'Huai Niu Xi','latin_name' => 'Achyranthis Bidentatae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Achyranthes root'],
            ['pinyin' => 'Huang Bai','latin_name' => 'Phellodendri Cortex','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Phellodendron bark'],
            ['pinyin' => 'Huang Jing','latin_name' => 'Polygonati Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Polygonatum root'],
            ['pinyin' => 'Huang Lian','latin_name' => 'Coptidis Rhizoma','concentration' => '5:1','costPerGram' => '0.38','common_name' => 'Coptis root'],
            ['pinyin' => 'Huang Qi','latin_name' => 'Astragali Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Astragalus root'],
            ['pinyin' => 'Huang Qi 10:1 Extract','latin_name' => 'Astragali Radix','concentration' => '10:1','costPerGram' => '0.30','common_name' => 'Astragalus root 10:1 Extract'],
            ['pinyin' => 'Huang Qi 100:1 Extract','latin_name' => 'Astragali Radix','concentration' => '100:1','costPerGram' => '0.50','common_name' => 'Astragalus root 100:1 Extract'],
            ['pinyin' => 'Huang Qi (Mi)','latin_name' => 'Astragali Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Honey-processed Astragalus'],
            ['pinyin' => 'Huang Qin','latin_name' => 'Scutellariae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Scutellaria root'],
            ['pinyin' => 'Huo Ma Ren','latin_name' => 'Cannabis Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Cannabis seed'],
            ['pinyin' => 'Huo Xiang','latin_name' => 'Pogostemonis Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Patchouli'],
            ['pinyin' => 'Bai Ji Li/Ci Ji Li/Ji Li','latin_name' => 'Tribuli Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Tribulus fruit'],
            ['pinyin' => 'Ci Ji Li/Bai Ji Li/Ji Li','latin_name' => 'Tribuli Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Tribulus fruit'],
            ['pinyin' => 'Ji Li/Bai Ji Li/Ci Ji Li','latin_name' => 'Tribuli Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Tribulus fruit'],
            ['pinyin' => 'Ji Nei Jin','latin_name' => 'Galli Gigeriae Endothelium Corneum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Gizzard lining'],
            ['pinyin' => 'Ji Xue Teng','latin_name' => 'Spatholobi Caulis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Spatholobus stem'],
            ['pinyin' => 'Jian Qu','latin_name' => 'Massa Medicata Fujianensis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Fujian leaven'],
            ['pinyin' => 'Jiang Can/Bai Jiang Can','latin_name' => 'Bombyx Batryticatus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Silkworm'],
            ['pinyin' => 'Bai Jiang Can/Jiang Can','latin_name' => 'Bombyx Batryticatus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Silkworm'],
            ['pinyin' => 'Jiang Huang','latin_name' => 'Curcumae Longae Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Turmeric'],
            ['pinyin' => 'Jiao Gu Lan','latin_name' => 'Gynostemmatis Rhizoma seu Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Gynostemma'],
            ['pinyin' => 'Jie Geng','latin_name' => 'Platycodonis Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Platycodon root'],
            ['pinyin' => 'Jin Qian Cao','latin_name' => 'Lysimachiae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Moneywort'],
            ['pinyin' => 'Jin Yin Hua','latin_name' => 'Lonicerae Flos','concentration' => '5:1','costPerGram' => '0.45','common_name' => 'Lonicera flower'],
            ['pinyin' => 'Jin Ying Zi','latin_name' => 'Rosae Laevigatae Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Cherokee rose fruit'],
            ['pinyin' => 'Jing Jie','latin_name' => 'Schizonepetae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Schizonepeta'],
            ['pinyin' => 'Jing Jie (Tan)','latin_name' => 'Schizonepetae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Charred Schizonepeta'],
            ['pinyin' => 'Jiu Cai Zi','latin_name' => 'Allii Tuberosi Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Chinese leek seed'],
            ['pinyin' => 'Ju He','latin_name' => 'Citri Reticulatae Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Tangerine Seed'],
            ['pinyin' => 'Ju Hong','latin_name' => 'Citri Reticulatae Pericarpium Rubrum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Red tangerine peel'],
            ['pinyin' => 'Ju Hua','latin_name' => 'Chrysanthemi Flos','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Chrysanthemum flower'],
            ['pinyin' => 'Ju Ye','latin_name' => 'Citri Reticulatae Folium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Tangerine leaf'],
            ['pinyin' => 'Jue Ming Zi','latin_name' => 'Cassiae Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Fetid cassia seed'],
            ['pinyin' => 'Ku Cai - Classical Pearls','latin_name' => 'Sonchus oleraceus','concentration' => '5:1','costPerGram' => '0.30','common_name' => 'Sow Thistle'],
            ['pinyin' => 'Ku Shen','latin_name' => 'Sophorae Flavescentis Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Flavescent sophora root'],
            ['pinyin' => 'Ku Shen Zi','latin_name' => 'Sophorae Flavescentis Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Flavescent sophora seed'],
            ['pinyin' => 'Kuan Dong Hua','latin_name' => 'Farfarae Flos','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Coltsfoot'],
            ['pinyin' => 'Kun Bu','latin_name' => 'Laminariae seu Eckloniae Thallus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Kelp'],
            ['pinyin' => 'Lai Fu Zi','latin_name' => 'Raphani Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Radish seed'],
            ['pinyin' => 'Li Zhi He','latin_name' => 'Litchi Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Litchee pit'],
            ['pinyin' => 'Lian Qiao','latin_name' => 'Forsythiae Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Forsythia fruit'],
            ['pinyin' => 'Lian Zi','latin_name' => 'Nelumbinis Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lotus fruit/seed'],
            ['pinyin' => 'Lian Zi Xin','latin_name' => 'Nelumbinis Plumula','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lotus plumule'],
            ['pinyin' => 'Ling Zhi','latin_name' => 'Ganoderma','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Ganoderma'],
            ['pinyin' => 'Ling Zhi 15:1 Extract','latin_name' => 'Ganoderma','concentration' => '*15:1','costPerGram' => '0.40','common_name' => 'Reishi 15 to 1 Extract'],
            ['pinyin' => 'LIU WEI DI HUANG WAN','latin_name' => 'LIU WEI DI HUANG WAN','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'LIU WEI DI HUANG WAN'],
            ['pinyin' => 'Long Chi','latin_name' => 'Mastodi Dentis Fossilia','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Dragon tooth'],
            ['pinyin' => 'Long Dan Cao','latin_name' => 'Gentianae Radix','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Gentian root'],
            ['pinyin' => 'LONG DAN XIE GAN TANG','latin_name' => 'LONG DAN XIE GAN TANG','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'LONG DAN XIE GAN TANG'],
            ['pinyin' => 'Long Gu','latin_name' => 'Mastodi Ossis Fossilia','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Dragon bone'],
            ['pinyin' => 'Long Gu Duan','latin_name' => 'Mastodi Ossis Fossilia','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Calcined Dragon bone'],
            ['pinyin' => 'Long Yan Rou','latin_name' => 'Longan Arillus','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Longan flesh'],
            ['pinyin' => 'Lu Gen','latin_name' => 'Phragmitis Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Phragmites root'],
            ['pinyin' => 'Lu Jiao','latin_name' => 'Cervi Cornu','concentration' => '5:1','costPerGram' => '0.75','common_name' => 'Deerhorn'],
            ['pinyin' => 'Lu Jiao Jiao','latin_name' => 'Cervi Cornus Colla','concentration' => '5:1','costPerGram' => '0.65','common_name' => 'Deer Antler Velvet'],
            ['pinyin' => 'Lu Jiao Shuang','latin_name' => 'Cervi Cornu Degelatinum','concentration' => '5:1','costPerGram' => '0.40','common_name' => 'Degelatinated deer antler'],
            ['pinyin' => 'Lu Lu Tong','latin_name' => 'Liquidambaris Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Liquidambar fruit'],
            ['pinyin' => 'Lu Rong','latin_name' => 'Cervi Cornu pantotrichum','concentration' => '5:1','costPerGram' => '0.80','common_name' => 'Deer Antler Velvet'],
            ['pinyin' => 'Luo Han Guo','latin_name' => 'Momordicae Fructus','concentration' => '5:1','costPerGram' => '0.36','common_name' => 'Momordica Fruit'],
            ['pinyin' => 'Luo Shi Teng','latin_name' => 'Trachelospermi Caulis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Star jasmine stem'],
            ['pinyin' => 'Ma Bo','latin_name' => 'Lasiosphaera','concentration' => '5:1','costPerGram' => '0.60','common_name' => 'Puffball'],
            ['pinyin' => 'Ma Chi Xian','latin_name' => 'Portulacae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Purslane'],
            ['pinyin' => 'Mai Men Dong / Mai Dong','latin_name' => 'Ophiopogonis Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Ophiopogon root'],
            ['pinyin' => 'Mai Ya','latin_name' => 'Hordei Fructus Germinatus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Barley sprout'],
            ['pinyin' => 'Man Jing Zi','latin_name' => 'Viticis Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Vitex fruit'],
            ['pinyin' => 'Mang Xiao','latin_name' => 'Natrii Sulfas','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Mirabilite'],
            ['pinyin' => 'Mei Gui Hua','latin_name' => 'Rosae Rugosae Flos','concentration' => '15:1','costPerGram' => '0.30','common_name' => 'Chinese Rose Flower extract'],
            ['pinyin' => 'Mi Meng Hua','latin_name' => 'Buddleiae Flos','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Buddleia flower bud'],
            ['pinyin' => 'Mi Wu - Classical Pearls','latin_name' => 'Ligusticum chuanxiong','concentration' => '5:1','costPerGram' => '0.40','common_name' => 'Ligusticum leaves'],
            ['pinyin' => 'Milk Thistle Seed','latin_name' => 'Silybum marianum','concentration' => '80% Silymarin','costPerGram' => '0.32','common_name' => 'Shui Fai Ji Extract'],
            ['pinyin' => 'Mo Han Lian / Han Lian Cao','latin_name' => 'Ecliptae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Eclipta'],
            ['pinyin' => 'Mo Yao','latin_name' => 'Myrrha','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Myrrh'],
            ['pinyin' => 'Mu Dan Pi','latin_name' => 'Moutan Cortex','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Moutan bark'],
            ['pinyin' => 'Mu Gua','latin_name' => 'Chaenomelis Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Chaenomeles fruit'],
            ['pinyin' => 'Mu Hu Die','latin_name' => 'Oroxyli Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Oroxylum Seed'],
            ['pinyin' => 'Mu Li','latin_name' => 'Ostreae Concha','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Oyster shell'],
            ['pinyin' => 'Mu Li Duan','latin_name' => 'Ostreae Concha','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Calcined Oyster shell'],
            ['pinyin' => 'Mu Tong (Chuan)','latin_name' => 'Clematidis armandii Caulis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Clematis armandi Stem'],
            ['pinyin' => 'Mu Tong - Akebia Extract','latin_name' => 'Akebia Trifoliata','concentration' => '8:1','costPerGram' => '0.20','common_name' => 'Akebia Stem Extract'],
            ['pinyin' => 'Mu Xiang','latin_name' => 'Aucklandiae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Costusroot'],
            ['pinyin' => 'Nan Sha Shen','latin_name' => 'Adenophorae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Adenophora root'],
            ['pinyin' => 'Nettle','latin_name' => 'Urtica Dioica','concentration' => '10:1','costPerGram' => '0.30','common_name' => 'Stinging Nettle Extract'],
            ['pinyin' => 'Ni Qiu - Classical Pearls','latin_name' => 'Misgurnus anguillicaudatus','concentration' => '5:1','costPerGram' => '0.40','common_name' => 'Dojo Loach'],
            ['pinyin' => 'Niu Bang Zi','latin_name' => 'Arctii Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Arctium seed'],
            ['pinyin' => 'Nu Zhen Zi','latin_name' => 'Ligustri Lucidi Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Ligustrum fruit'],
            ['pinyin' => 'Nuo Dao Gen','latin_name' => 'Oryzae Glutinosae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Glutinous rice root'],
            ['pinyin' => 'Ou Jie','latin_name' => 'Nelumbinis Nodus rhizomatis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lotus Root node'],
            ['pinyin' => 'Pang Da Hai','latin_name' => 'Sterculiae Lychnophorae Semen','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Sterculia'],
            ['pinyin' => 'Pao Jiang','latin_name' => 'Zingiberis Rhizoma Praeparatum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Blast-fried ginger'],
            ['pinyin' => 'Pei Lan','latin_name' => 'Eupatorii Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Eupatorium'],
            ['pinyin' => 'Pi Pa Ye','latin_name' => 'Eriobotryae Folium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Loquat leaf'],
            ['pinyin' => 'Pu Bu Zi Ye','latin_name' => 'Folium Cordia Dichotoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Sebastan Plum Cordia'],
            ['pinyin' => 'Pu Gong Ying','latin_name' => 'Taraxaci Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Dandelion'],
            ['pinyin' => 'Pu Huang','latin_name' => 'Typhae Pollen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Typha pollen'],
            ['pinyin' => 'Pu Huang (Tan)','latin_name' => 'Typhae Pollen Carbonisatum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Charred Typha pollen'],
            ['pinyin' => 'Pu Tao Zi','latin_name' => 'Vitis vinifera','concentration' => '5:1','costPerGram' => '0.30','common_name' => 'Grape Seed'],
            ['pinyin' => 'Qian Cao','latin_name' => 'Rubiae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Madder root'],
            ['pinyin' => 'Qian Hu','latin_name' => 'Peucedani Radix','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Peucedanum root'],
            ['pinyin' => 'Qian Shi','latin_name' => 'Euryales Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Euryale seed'],
            ['pinyin' => 'Qiang Huo','latin_name' => 'Notopterygii Rhizoma et Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Notopterygium root'],
            ['pinyin' => 'Qin Jiao','latin_name' => 'Gentianae macrophyllae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Large gentian root'],
            ['pinyin' => 'Qin Pi','latin_name' => 'Fraxini Cortex','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Ash bark'],
            ['pinyin' => 'Qing Dai','latin_name' => 'Indigo Naturalis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Indigo'],
            ['pinyin' => 'Qing Dai - Classical Pearls','latin_name' => 'Indigo naturalis','concentration' => '5:1','costPerGram' => '0.36','common_name' => 'Paozhi Indigo powder'],
            ['pinyin' => 'Qing Hao','latin_name' => 'Artemisiae Annuae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Sweet wormwood'],
            ['pinyin' => 'Qing Pi','latin_name' => 'Citri Reticulatae Pericarpium Viride','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Unripe tangerine peel'],
            ['pinyin' => 'Qu Mai','latin_name' => 'Dianthi Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Dianthus'],
            ['pinyin' => 'Quan Xie','latin_name' => 'Scorpio','concentration' => '5:1','costPerGram' => '0.85','common_name' => 'Scorpion'],
            ['pinyin' => 'Ren Dong Teng','latin_name' => 'Lonicera Caulis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lonicera stem'],
            ['pinyin' => 'Ren Shen (Hong)','latin_name' => 'Panax Ginseng Radix','concentration' => '5:1','costPerGram' => '0.60','common_name' => 'Ginseng Root'],
            ['pinyin' => 'Ren Shen (Bai)- ORGANIC','latin_name' => 'Panax Ginseng Radix','concentration' => '3:1','costPerGram' => '0.45','common_name' => 'Ginseng Root'],
            ['pinyin' => 'Rou Cong Rong','latin_name' => 'Cistanches Herba','concentration' => '5:1','costPerGram' => '0.38','common_name' => 'Cistanche'],
            ['pinyin' => 'Rou Dou Kou','latin_name' => 'Myristicae Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Nutmeg'],
            ['pinyin' => 'Rou Gui','latin_name' => 'Cinnamomi Cortex','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Cinnamon bark'],
            ['pinyin' => 'Rou Gui (Yuenan) - Classical Pearls','latin_name' => 'Cinnamomi Cortex','concentration' => '5:1','costPerGram' => '0.88','common_name' => 'Vietnamese Cinnamon bark'],
            ['pinyin' => 'Ru Xiang','latin_name' => 'Olibanum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Frankincense'],
            ['pinyin' => 'San Leng','latin_name' => 'Sparganii Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Sparganium root'],
            ['pinyin' => 'San Qi','latin_name' => 'Notoginseng Radix','concentration' => '*1:1','costPerGram' => '0.40','common_name' => 'Notoginseng root'],
            ['pinyin' => 'Sang Bai Pi','latin_name' => 'Mori Cortex','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Mulberry bark'],
            ['pinyin' => 'Sang Ji Sheng','latin_name' => 'Taxilli Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Mistletoe'],
            ['pinyin' => 'Sang Piao Xiao','latin_name' => 'Mantidis Ootheca','concentration' => '5:1','costPerGram' => '0.60','common_name' => 'Mantis egg-case'],
            ['pinyin' => 'Sang Shen','latin_name' => 'Mori Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Mulberry'],
            ['pinyin' => 'Sang Ye','latin_name' => 'Mori Folium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Mulberry leaf'],
            ['pinyin' => 'Sang Zhi','latin_name' => 'Mori Ramulus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Mulberry twig'],
            ['pinyin' => 'Sha Ren','latin_name' => 'Amomi Fructus','concentration' => '5:1','costPerGram' => '0.34','common_name' => 'Amomum fruit'],
            ['pinyin' => 'Sha Ren (Xi) - Classical Pearls','latin_name' => 'Amomi Fructus','concentration' => '5:1','costPerGram' => '0.70','common_name' => 'Burmese Amomum'],
            ['pinyin' => 'Sha Yuan Zi','latin_name' => 'Astragali Complanati Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Complanate astragalus seed'],
            ['pinyin' => 'Shan Ci Gu','latin_name' => 'Cremastrae/Pleiones Pseudobulbus','concentration' => '5:1','costPerGram' => '0.50','common_name' => 'Cremastra/pleione pseudobulb'],
            ['pinyin' => 'Shan Dou Gen','latin_name' => 'Sophorae Tonkinensis Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Bushy sophora root'],
            ['pinyin' => 'Shan Yao','latin_name' => 'Dioscoreae Rhizoma','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Dioscorea root'],
            ['pinyin' => 'Shan Zha','latin_name' => 'Crataegi Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Crataegus fruit'],
            ['pinyin' => 'Shan Zha Jiao','latin_name' => 'Crataegi Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Scorch-fried Crataegus fruit'],
            ['pinyin' => 'Shan Zhu Yu','latin_name' => 'Corni Fructus','concentration' => '5:1','costPerGram' => '0.30','common_name' => 'Cornus fruit'],
            ['pinyin' => 'SHAO FU ZHU YU TANG','latin_name' => 'SHAO FU ZHU YU TANG','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'SHAO FU ZHU YU TANG'],
            ['pinyin' => 'She Chuang Zi','latin_name' => 'Cnidii Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Cnidium seed'],
            ['pinyin' => 'She Gan','latin_name' => 'Belamcandae Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Belamcanda root'],
            ['pinyin' => 'Shen Jin Cao','latin_name' => 'Lycopodii Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Ground pine'],
            ['pinyin' => 'SHEN LING BAI ZHU SAN','latin_name' => 'SHEN LING BAI ZHU SAN','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'SHEN LING BAI ZHU SAN'],
            ['pinyin' => 'Shen Qu','latin_name' => 'Massa Medicata Fermentata','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Medicated leaven'],
            ['pinyin' => 'SHEN TONG ZHU YU TANG','latin_name' => 'SHEN TONG ZHU YU TANG','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'SHEN TONG ZHU YU TANG'],
            ['pinyin' => 'Sheng Di Huang','latin_name' => 'Rehmanniae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Dried/fresh rehmannia root'],
            ['pinyin' => 'Sheng Jiang','latin_name' => 'Zingiberis Rhizoma Recens','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Fresh ginger'],
            ['pinyin' => 'Sheng Jiang Pi','latin_name' => 'Zingiberis Rhizoma Cortex','concentration' => '5:1','costPerGram' => '0.30','common_name' => 'Fresh Ginger Peel'],
            ['pinyin' => 'Sheng Ma','latin_name' => 'Cimicifugae Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Cimicifuga root'],
            ['pinyin' => 'Shi Chang Pu','latin_name' => 'Acori Tatarinowii Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Acorus root'],
            ['pinyin' => 'Shi Gao','latin_name' => 'Gypsum Fibrosum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Gypsum'],
            ['pinyin' => 'Shi Hu','latin_name' => 'Dendrobii Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Dendrobium'],
            ['pinyin' => 'Shi Jue Ming','latin_name' => 'Haliotidis Concha','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Abalone shell'],
            ['pinyin' => 'Shi Liu Pi','latin_name' => 'Granati Pericarpium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Pomegranite Rind'],
            ['pinyin' => 'Shi Wei','latin_name' => 'Pyrrosiae Folium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Pyrrosia leaf'],
            ['pinyin' => 'Shu Di Huang','latin_name' => 'Rehmanniae Radix Praeparata','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Cooked rehmannia root'],
            ['pinyin' => 'Shui Fai Ji','latin_name' => 'Silybum marianum','concentration' => '80% Silymarin','costPerGram' => '0.32','common_name' => 'Milk Thistle Seed'],
            ['pinyin' => 'Shui Zhi','latin_name' => 'Hirudo','concentration' => '5:1','costPerGram' => '0.50','common_name' => 'Leech'],
            ['pinyin' => 'Si Gua Luo','latin_name' => 'Luffae Fructus Retinervus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Loofah'],
            ['pinyin' => 'SI JUN ZI TANG','latin_name' => 'SI JUN ZI TANG','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'SI JUN ZI TANG'],
            ['pinyin' => 'SI WU TANG','latin_name' => 'SI WU TANG','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'SI WU TANG'],
            ['pinyin' => 'Su Mu','latin_name' => 'Sappan Lignum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Sappan wood'],
            ['pinyin' => 'SU ZI JIANG QI TANG','latin_name' => 'SU ZI JIANG QI TANG','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'SU ZI JIANG QI TANG'],
            ['pinyin' => 'Suan Zao Ren','latin_name' => 'Ziziphi Spinosi Semen','concentration' => '5:1','costPerGram' => '0.34','common_name' => 'Spiny jujube kernel'],
            ['pinyin' => 'SI NI SAN','latin_name' => 'SI NI SAN','concentration' => '5:1','costPerGram' => '.25','common_name' => 'SI NI SAN'],
            ['pinyin' => 'Suo Yang','latin_name' => 'Cynomorii Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Cynomorium'],
            ['pinyin' => 'Tai Zi Shen','latin_name' => 'Pseudostellariae Radix','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Pseudostellaria root'],
            ['pinyin' => 'Tan Xiang','latin_name' => 'Santali Albi Lignum','concentration' => '5:1','costPerGram' => '0.34','common_name' => 'Sandalwood'],
            ['pinyin' => 'Tao Ren','latin_name' => 'Persicae Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Peach kernel'],
            ['pinyin' => 'Tian Hua Fen','latin_name' => 'Trichosanthis Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Trichosanthes root'],
            ['pinyin' => 'Tian Kui Zi','latin_name' => 'Semiaquilegiae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Semiaquilegia root'],
            ['pinyin' => 'Tian Ma','latin_name' => 'Gastrodiae Rhizoma','concentration' => '5:1','costPerGram' => '0.65','common_name' => 'Gastrodia root'],
            ['pinyin' => 'TIAN MA GOU TENG YIN','latin_name' => 'TIAN MA GOU TENG YIN','concentration' => '5:1','costPerGram' => '0.30','common_name' => 'TIAN MA GOU TENG YIN'],
            ['pinyin' => 'Tian Men Dong / Tian Dong','latin_name' => 'Asparagi Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Asparagus root'],
            ['pinyin' => 'Tian Nan Xing','latin_name' => 'Arisaematis Rhizoma','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Arisaema root'],
            ['pinyin' => 'Tian Zhu Huang','latin_name' => 'Bambusae concretio silicea','concentration' => '5:1','costPerGram' => '0.40','common_name' => 'Bamboo Silicea'],
            ['pinyin' => 'Ting Li Zi','latin_name' => 'Lepidii/Descurainiae Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lepidium/descurainiae'],
            ['pinyin' => 'Tong Cao','latin_name' => 'Tetrapanacis Medulla','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Xiao'],
            ['pinyin' => 'Tu Fu Ling','latin_name' => 'Smilacis Glabrae Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Smooth greenbrier root'],
            ['pinyin' => 'Tu Si Zi','latin_name' => 'Cuscutae Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Cuscuta seed'],
            ['pinyin' => 'Wa Leng Zi','latin_name' => 'Arcae Concha','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Ark shell'],
            ['pinyin' => 'Wang Bu Liu Xing','latin_name' => 'Vaccariae Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Vaccaria seed'],
            ['pinyin' => 'Wang Gua Classical Pearls','latin_name' => 'Trichosanthes cucumeroides','concentration' => '5:1','costPerGram' => '0.60','common_name' => 'Snake Gourd'],
            ['pinyin' => 'Wei Ling Xian','latin_name' => 'Clematidis Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Clematis root'],
            ['pinyin' => 'Wu Bei Zi','latin_name' => 'Galla chinensis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Gallnut of Chinese Sumac'],
            ['pinyin' => 'Wu Gong','latin_name' => 'Scolopendra','concentration' => '5:1','costPerGram' => '1.00','common_name' => 'Centipede'],
            ['pinyin' => 'Wu Jia Pi','latin_name' => 'Acanthopanacis Cortex','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Acanthopanax'],
            ['pinyin' => 'Wu Ling Zhi','latin_name' => 'Trogopterori Faeces','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Flying Squirrel Droppings'],
            ['pinyin' => 'Wu Mei','latin_name' => 'Mume Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Mume fruit'],
            ['pinyin' => 'Wu Shao She','latin_name' => 'Zaocys','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Zaocys'],
            ['pinyin' => 'Wu Tou/Chuan Wu Zhi - Classical Pearls','latin_name' => 'Aconiti carmicheli Radix','concentration' => '5:1','costPerGram' => '0.45','common_name' => 'Jiangyou Fuyang Aconite mother root'],
            ['pinyin' => 'Wu Wei Zi','latin_name' => 'Schisandrae Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Schisandra berry'],
            ['pinyin' => 'Wu Yao','latin_name' => 'Linderae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lindera root'],
            ['pinyin' => 'Wu Zhu Yu','latin_name' => 'Evodiae Fructus','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Evodia fruit'],
            ['pinyin' => 'Wu Zhu Yu - Classical Pearls','latin_name' => 'Evodiae fructus','concentration' => '5:1','costPerGram' => '0.40','common_name' => 'Sichuan Fuyang Evodia'],
            ['pinyin' => 'Xi Xian Cao','latin_name' => 'Siegesbeckiae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Siegesbeckia'],
            ['pinyin' => 'Xi Xin','latin_name' => 'Asari Herba','concentration' => '5:1','costPerGram' => '0.40','common_name' => 'Asarum Wild Ginger'],
            ['pinyin' => 'Maca Root - Organic, gelatinized','latin_name' => 'Lepidium meyenii','concentration' => '1:1','costPerGram' => '.20','common_name' => 'Maca Root'],
            ['pinyin' => 'Xi Xin 10:1 Extract','latin_name' => 'Asari Herba','concentration' => '*10:1','costPerGram' => '0.40','common_name' => 'Asarum Wild Ginger 10 to 1 Extract'],
            ['pinyin' => 'Xi Yang Shen Extract','latin_name' => 'Panacis Quinquefolii Radix','concentration' => '1:1','costPerGram' => '0.25','common_name' => 'American ginseng'],
            ['pinyin' => 'Xi Yang Shen Powdered Root - ORGANIC','latin_name' => 'Panacis Quinquefolii Radix','concentration' => '1:1','costPerGram' => '.30','common_name' => 'American ginseng'],
            ['pinyin' => 'Xia Ku Cao','latin_name' => 'Prunellae Spica','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Prunella spike'],
            ['pinyin' => 'Xian He Cao','latin_name' => 'Agrimoniae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Agrimony'],
            ['pinyin' => 'Xian Mao','latin_name' => 'Curculiginis Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Curculigo root'],
            ['pinyin' => 'Xiang Fu','latin_name' => 'Cyperi Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Cyperus root'],
            ['pinyin' => 'Xiang Ru','latin_name' => 'Moslae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Glossogyne'],
            ['pinyin' => 'XIAO CHAI HU TANG','latin_name' => 'XIAO CHAI HU TANG','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'XIAO CHAI HU TANG'],
            ['pinyin' => 'XIAO CHENG QI TANG','latin_name' => 'XIAO CHENG QI TANG','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'XIAO CHENG QI TANG'],
            ['pinyin' => 'Xiao Hui Xiang','latin_name' => 'Foeniculi Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Fennel fruit'],
            ['pinyin' => 'Xiao Ji','latin_name' => 'Cirsii Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Field Thistle'],
            ['pinyin' => 'Xiao Mai','latin_name' => 'Tritici Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Wheat'],
            ['pinyin' => 'Xie Bai','latin_name' => 'Allii Macrostemonis Bulbus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Chinese chive bulb'],
            ['pinyin' => 'Xin Yi Hua','latin_name' => 'Magnoliae Flos','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Magnolia flower'],
            ['pinyin' => 'Xing Ren','latin_name' => 'Armeniacae Semen (Armeniacae Semen Amarum)','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Apricot kernel'],
            ['pinyin' => 'XIAO YAO SAN','latin_name' => 'XIAO YAO SAN','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'XIAO YAO SAN'],
            ['pinyin' => 'Xu Chang Qing','latin_name' => 'Cynachi paniculati Radix','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Paniculate cynanchum root'],
            ['pinyin' => 'Xu Duan','latin_name' => 'Dipsaci Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Dipsacus root'],
            ['pinyin' => 'Xuan Fu Hua','latin_name' => 'Inulae Flos','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Inula flower'],
            ['pinyin' => 'Xuan Shen','latin_name' => 'Scrophulariae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Scrophularia root'],
            ['pinyin' => 'XUE FU ZHU YU TANG','latin_name' => 'XUE FU ZHU YU TANG','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'XUE FU ZHU YU TANG'],
            ['pinyin' => 'Yan Hu Suo','latin_name' => 'Corydalis Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Corydalis root'],
            ['pinyin' => 'Yang Shen - Classical Pearls','latin_name' => 'Capra hircus','concentration' => '5:1','costPerGram' => '0.55','common_name' => 'Kidneys, penis, and testicles of grass-fed male go'],
            ['pinyin' => 'Ye Jiao Teng/Shou Wu Teng','latin_name' => 'Polygoni Multiflori Caulis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Flowery knotweed stem'],
            ['pinyin' => 'Shou Wu Teng/Ye Jiao Tang','latin_name' => 'Polygoni Multiflori Caulis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Flowery knotweed stem'],
            ['pinyin' => 'Ye Ju Hua','latin_name' => 'Chrysanthemi Indici Flos','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Wild chrysanthemum flower'],
            ['pinyin' => 'Yi Mu Cao','latin_name' => 'Leonuri Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Leonurus'],
            ['pinyin' => 'Yi Yi Ren','latin_name' => 'Coicis Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Coix seed'],
            ['pinyin' => 'Yi Yi Ren Chao','latin_name' => 'Coicis Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Stir-fried Coix seed'],
            ['pinyin' => 'Yi Zhi Ren','latin_name' => 'Alpiniae oxyphyllae Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Alpinia fruit'],
            ['pinyin' => 'Yin Chai Hu','latin_name' => 'Stellariae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Stellaria'],
            ['pinyin' => 'Yin Chen Hao','latin_name' => 'Artemisiae Scopariae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Virgate wormwood'],
            ['pinyin' => 'YIN QIAO SAN','latin_name' => 'YIN QIAO SAN','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'YIN QIAO SAN'],
            ['pinyin' => 'Yin Xing Ye','latin_name' => 'Ginkgo foilum','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Ginkgo Leaf'],
            ['pinyin' => 'Yin Yang Huo','latin_name' => 'Epimedii Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Epimedium'],
            ['pinyin' => 'Yin Yang Huo - Classical Pearls','latin_name' => 'Epimedii herba','concentration' => '5:1','costPerGram' => '0.40','common_name' => 'Shaanxi Fuyang Epimedium'],
            ['pinyin' => 'YOU GUI WAN','latin_name' => 'YOU GUI WAN','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'YOU GUI WAN'],
            ['pinyin' => 'Yu Jin','latin_name' => 'Curcumae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Curcuma root'],
            ['pinyin' => 'Yu Li Ren','latin_name' => 'Pruni Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Bush Cherry Kernel'],
            ['pinyin' => 'Yu Mi Xu','latin_name' => 'Maydis Stigma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Corn silk'],
            ['pinyin' => 'Yu Xing Cao','latin_name' => 'Houttuyniae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Houttuynia'],
            ['pinyin' => 'Yuan Zhi','latin_name' => 'Polygalae Radix','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Polygala root'],
            ['pinyin' => 'Zao Jiao Ci','latin_name' => 'Gleditsiae Spina','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Gleditsia thorn'],
            ['pinyin' => 'Ze Lan','latin_name' => 'Lycopi Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Lycopus'],
            ['pinyin' => 'Ze Xie','latin_name' => 'Alismatis Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Alisma tuber'],
            ['pinyin' => 'Zhe Bei Mu','latin_name' => 'Fritillariae Thunbergii Bulbus','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Zhejiang fritillaria bulb'],
            ['pinyin' => 'Zhen Zhu','latin_name' => 'Margarita','concentration' => '1:1','costPerGram' => '0.55','common_name' => 'Pearl Powder Extract'],
            ['pinyin' => 'Zhen Zhu Mu','latin_name' => 'Concha Margaritifera','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Mother-of-pearl'],
            ['pinyin' => 'ZHI BAI DI HUANG WAN','latin_name' => 'ZHI BAI DI HUANG WAN','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'ZHI BAI DI HUANG WAN'],
            ['pinyin' => 'Zhi Gan Cao','latin_name' => 'Glycyrrhizae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Honey-fried licorice root'],
            ['pinyin' => 'Zhi Gan Cao - Classical Pearls','latin_name' => 'Glycyrrhizae Radix','concentration' => '5:1','costPerGram' => '0.40','common_name' => 'Gansu yitang-fried licorice root'],
            ['pinyin' => 'Zhi Ke','latin_name' => 'Aurantii Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Bitter orange'],
            ['pinyin' => 'Zhi Mu','latin_name' => 'Anemarrhenae Rhizoma','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Anemarrhena root'],
            ['pinyin' => 'Zhi Shi','latin_name' => 'Aurantii Fructus Immaturus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Unripe bitter orange'],
            ['pinyin' => 'Zhi Zi','latin_name' => 'Gardeniae Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Gardenia fruit'],
            ['pinyin' => 'Zhi Zi Tan/Jiao','latin_name' => 'Gardeniae Fructus Praeparatus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Charred/Brown Gardenia fruit'],
            ['pinyin' => 'Zhu Ling','latin_name' => 'Polyporus','concentration' => '5:1','costPerGram' => '0.36','common_name' => 'Polyporus'],
            ['pinyin' => 'Zhu Ru','latin_name' => 'Bambusae Caulis in Taenia','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Bamboo shavings'],
            ['pinyin' => 'Zi Cao','latin_name' => 'Arnebiae/Lithospermi Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Arnebia/Lithospermium'],
            ['pinyin' => 'Zi Hua Di Ding','latin_name' => 'Violae Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Violet'],
            ['pinyin' => 'Zi Ran Tong','latin_name' => 'Pyritum','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Pyrite'],
            ['pinyin' => 'Zi Su Geng','latin_name' => 'Perillae Caulis','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Perilla stem'],
            ['pinyin' => 'Zi Su Ye','latin_name' => 'Perillae Folium','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Perilla leaf'],
            ['pinyin' => 'Zi Su Zi','latin_name' => 'Perillae Fructus','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Perilla fruit'],
            ['pinyin' => 'Zi Wan','latin_name' => 'Asteris Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Aster root'],
            ['pinyin' => 'ZUO GUI YIN','latin_name' => 'ZUO GUI YIN','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'ZUO GUI YIN'],
            ['pinyin' => 'Shi Di','latin_name' => 'Calyx','concentration' => '5:1','costPerGram' => '.20','common_name' => 'Persimmon Calyx'],
            ['pinyin' => 'Er Cha','latin_name' => 'Acacia Catechu','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Catechu'],
            ['pinyin' => 'Qian Cao (Tan)','latin_name' => 'Rubiae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Charred Madder Root'],
            ['pinyin' => 'Ban Bian Lian','latin_name' => 'Lobeliae Chinensis Herba','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Chinese Lobelia'],
            ['pinyin' => 'Cao Dou Kou','latin_name' => 'Alpiniae Katsumadai Semen','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Katsumada\'s galangal seed'],
            ['pinyin' => 'BU ZHONG YI QI TANG (not cooked together)','latin_name' => 'BU ZHONG YI QI TANG (not cooked together)','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'BU ZHONG YI QI TANG (not cooked together)'],
            ['pinyin' => 'BU ZHONG YI QI TANG','latin_name' => 'BU ZHONG YI QI TANG','concentration' => '5:1','costPerGram' => '0.30','common_name' => 'BU ZHONG YI QI TANG'],
            ['pinyin' => 'CHAI HU JIA LONG GU MU LI TANG (not cooked togethe','latin_name' => 'CHAI HU JIA LONG GU MU LI TANG (not cooked togethe','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'CHAI HU JIA LONG GU MU LI TANG (not cooked togethe'],
            ['pinyin' => 'Fo Shou','latin_name' => 'Citri Sarcodactylis Fructus','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'Buddha\'s hand fruit'],
            ['pinyin' => 'GE HUA JIE CHANG SAN','latin_name' => 'GE HUA JIE CHANG SAN','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'GE HUA JIE CHANG SAN'],
            ['pinyin' => 'JIA WEI XIAO YAO SAN','latin_name' => 'JIA WEI XIAO YAO SAN','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'JIA WEI XIAO YAO SAN'],
            ['pinyin' => 'Ji Cai','latin_name' => 'Capsella bursa-pastoris','concentration' => '5:1','costPerGram' => '0.42','common_name' => 'Shephards Purse'],
            ['pinyin' => 'SANG PIAO XIAO SAN (not cooked together)','latin_name' => 'SANG PIAO XIAO SAN (not cooked together)','concentration' => '5:1','costPerGram' => '.28','common_name' => 'SANG PIAO XIAO SAN (not cooked together)'],
            ['pinyin' => 'Liu Ji Niu','latin_name' => 'Artemesiae anomalae Herba','concentration' => '5:1','costPerGram' => '.20','common_name' => 'Anomalous artemisia'],
            ['pinyin' => 'Lu Feng Fang','latin_name' => 'Vespae','concentration' => '5:1','costPerGram' => '.32','common_name' => 'Hornet\'s nest'],
            ['pinyin' => 'Luo Bu Ma','latin_name' => 'Herba Apocyni Veneti','concentration' => '5:1','costPerGram' => '.25','common_name' => 'Dogbane Leaf'],
            ['pinyin' => 'Sha Shen (Bei)','latin_name' => 'Adenophorae seu Glehniae Radix','concentration' => '5:1','costPerGram' => '0.20','common_name' => 'Glehnia root'],
            ['pinyin' => 'Niu Xi (Huai)','latin_name' => 'Achyranthis Bidentatae Radix','concentration' => '5:1','costPerGram' => '.20','common_name' => 'Achyranthes root'],
            ['pinyin' => 'SHA SHEN MAI DONG TANG (not cooked together)','latin_name' => 'SHA SHEN MAI DONG TANG (not cooked together)','concentration' => '5:1','costPerGram' => '0.25','common_name' => 'SHA SHEN MAI DONG TANG (not cooked together)'],
            ['pinyin' => 'Xue Jie','latin_name' => 'Draconis Sanguis','concentration' => '5:1','costPerGram' => '.40','common_name' => 'Dragon\'s Blood'],
            ['pinyin' => 'Yu Zhu','latin_name' => 'Polygonati Odorati Rhizoma','concentration' => '5:1','costPerGram' => '.20','common_name' => 'Solomon\'s seal root'],
            ['pinyin' => 'WEN DAN TANG','latin_name' => 'WEN DAN TANG','concentration' => '5:1','costPerGram' => '.20','common_name' => 'WEN DAN TANG'],
            ['pinyin' => 'YI GUAN JIAN','latin_name' => 'YI GUAN JIAN','concentration' => '5:1','costPerGram' => '.25','common_name' => 'YI GUAN JIAN'],
            ['pinyin' => 'Mu Tong (Chuan) - Nong\'s','latin_name' => 'Clematidis armandii Caulis','concentration' => '5:1','costPerGram' => '.20','common_name' => 'Clematis armandi'],
            ['pinyin' => 'Xi Xin - Nong\'s','latin_name' => 'Asari Herba','concentration' => '5:1','costPerGram' => '.40','common_name' => 'Asarum Wild Ginger'],
            

        ]);
    }
}
